/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_ge.h"

bool_t
xdr_AccessRequest (XDR *xdrs, AccessRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user_id, 50))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->authorization_token, 100))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->refresh))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valabil))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_AccessResponse (XDR *xdrs, AccessResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->response_type, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, 100))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->validity_period))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DelegatedActionRequest (XDR *xdrs, DelegatedActionRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->action, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, 100))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->autoRefresh))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DelegatedActionResponse (XDR *xdrs, DelegatedActionResponse *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->response, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->new_acc_token, 100))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->new_refr_token, 100))
		 return FALSE;
	return TRUE;
}
